version: '3'

services:
  db:
    image: postgres:15.2-alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: my-nestjs-app
    ports:
      - "3000:3000"
    # volumes:
    #   - ./src:/app/src

volumes:
  databse: